#!/bin/bash
PARCEL_INSTALL=$PARCELS_ROOT/$PARCEL_DIRNAME
if [ -z "$TRINO_PLUGINS"]; then
  echo "TRINO_PLUGINS not set, setting var"
  export TRINO_PLUGINS="$PARCEL_INSTALL"
else
  echo "TRINO_PLUGINS alread set, $TRINO_PLUGINS"
  export TRINO_PLUGINS="$TRINO_PLUGINS:$PARCEL_INSTALL"
fi
echo "New TRINO_PLUGINS, $TRINO_PLUGINS"